// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tiappb.proto

package tiappb

import (
	"fmt"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	aprpcpb "github.com/tutububug/kvproto/pkg/aprpcpb"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tiap service

type TiapClient interface {
	RawGet(ctx context.Context, in *aprpcpb.RawGetRequest, opts ...grpc.CallOption) (*aprpcpb.RawGetResponse, error)
	RawGetKeyTTL(ctx context.Context, in *aprpcpb.RawGetKeyTTLRequest, opts ...grpc.CallOption) (*aprpcpb.RawGetKeyTTLResponse, error)
	RawPut(ctx context.Context, in *aprpcpb.RawPutRequest, opts ...grpc.CallOption) (*aprpcpb.RawPutResponse, error)
	RawPutWithTTL(ctx context.Context, in *aprpcpb.RawPutWithTTLRequest, opts ...grpc.CallOption) (*aprpcpb.RawPutWithTTLResponse, error)
	RawDelete(ctx context.Context, in *aprpcpb.RawDeleteRequest, opts ...grpc.CallOption) (*aprpcpb.RawDeleteResponse, error)
	RawDeleteRange(ctx context.Context, in *aprpcpb.RawDeleteRangeRequest, opts ...grpc.CallOption) (*aprpcpb.RawDeleteRangeResponse, error)
	RawScan(ctx context.Context, in *aprpcpb.RawScanRequest, opts ...grpc.CallOption) (*aprpcpb.RawScanResponse, error)
	RawReverseScan(ctx context.Context, in *aprpcpb.RawScanRequest, opts ...grpc.CallOption) (*aprpcpb.RawScanResponse, error)
	RawCompareAndSwap(ctx context.Context, in *aprpcpb.RawCASRequest, opts ...grpc.CallOption) (*aprpcpb.RawCASResponse, error)
	RawBatchGet(ctx context.Context, in *aprpcpb.RawBatchGetRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchGetResponse, error)
	RawBatchPut(ctx context.Context, in *aprpcpb.RawBatchPutRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchPutResponse, error)
	RawBatchDelete(ctx context.Context, in *aprpcpb.RawBatchDeleteRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchDeleteResponse, error)
}

type tiapClient struct {
	cc *grpc.ClientConn
}

func NewTiapClient(cc *grpc.ClientConn) TiapClient {
	return &tiapClient{cc}
}

func (c *tiapClient) RawGet(ctx context.Context, in *aprpcpb.RawGetRequest, opts ...grpc.CallOption) (*aprpcpb.RawGetResponse, error) {
	out := new(aprpcpb.RawGetResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawGetKeyTTL(ctx context.Context, in *aprpcpb.RawGetKeyTTLRequest, opts ...grpc.CallOption) (*aprpcpb.RawGetKeyTTLResponse, error) {
	out := new(aprpcpb.RawGetKeyTTLResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawGetKeyTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawPut(ctx context.Context, in *aprpcpb.RawPutRequest, opts ...grpc.CallOption) (*aprpcpb.RawPutResponse, error) {
	out := new(aprpcpb.RawPutResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawPutWithTTL(ctx context.Context, in *aprpcpb.RawPutWithTTLRequest, opts ...grpc.CallOption) (*aprpcpb.RawPutWithTTLResponse, error) {
	out := new(aprpcpb.RawPutWithTTLResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawPutWithTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawDelete(ctx context.Context, in *aprpcpb.RawDeleteRequest, opts ...grpc.CallOption) (*aprpcpb.RawDeleteResponse, error) {
	out := new(aprpcpb.RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawDeleteRange(ctx context.Context, in *aprpcpb.RawDeleteRangeRequest, opts ...grpc.CallOption) (*aprpcpb.RawDeleteRangeResponse, error) {
	out := new(aprpcpb.RawDeleteRangeResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawDeleteRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawScan(ctx context.Context, in *aprpcpb.RawScanRequest, opts ...grpc.CallOption) (*aprpcpb.RawScanResponse, error) {
	out := new(aprpcpb.RawScanResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawReverseScan(ctx context.Context, in *aprpcpb.RawScanRequest, opts ...grpc.CallOption) (*aprpcpb.RawScanResponse, error) {
	out := new(aprpcpb.RawScanResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawReverseScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawCompareAndSwap(ctx context.Context, in *aprpcpb.RawCASRequest, opts ...grpc.CallOption) (*aprpcpb.RawCASResponse, error) {
	out := new(aprpcpb.RawCASResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawCompareAndSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawBatchGet(ctx context.Context, in *aprpcpb.RawBatchGetRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchGetResponse, error) {
	out := new(aprpcpb.RawBatchGetResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawBatchGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawBatchPut(ctx context.Context, in *aprpcpb.RawBatchPutRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchPutResponse, error) {
	out := new(aprpcpb.RawBatchPutResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawBatchPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) RawBatchDelete(ctx context.Context, in *aprpcpb.RawBatchDeleteRequest, opts ...grpc.CallOption) (*aprpcpb.RawBatchDeleteResponse, error) {
	out := new(aprpcpb.RawBatchDeleteResponse)
	err := c.cc.Invoke(ctx, "/tiappb.Tiap/RawBatchDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tiap service

type TiapServer interface {
	RawGet(context.Context, *aprpcpb.RawGetRequest) (*aprpcpb.RawGetResponse, error)
	RawGetKeyTTL(context.Context, *aprpcpb.RawGetKeyTTLRequest) (*aprpcpb.RawGetKeyTTLResponse, error)
	RawPut(context.Context, *aprpcpb.RawPutRequest) (*aprpcpb.RawPutResponse, error)
	RawPutWithTTL(context.Context, *aprpcpb.RawPutWithTTLRequest) (*aprpcpb.RawPutWithTTLResponse, error)
	RawDelete(context.Context, *aprpcpb.RawDeleteRequest) (*aprpcpb.RawDeleteResponse, error)
	RawDeleteRange(context.Context, *aprpcpb.RawDeleteRangeRequest) (*aprpcpb.RawDeleteRangeResponse, error)
	RawScan(context.Context, *aprpcpb.RawScanRequest) (*aprpcpb.RawScanResponse, error)
	RawReverseScan(context.Context, *aprpcpb.RawScanRequest) (*aprpcpb.RawScanResponse, error)
	RawCompareAndSwap(context.Context, *aprpcpb.RawCASRequest) (*aprpcpb.RawCASResponse, error)
	RawBatchGet(context.Context, *aprpcpb.RawBatchGetRequest) (*aprpcpb.RawBatchGetResponse, error)
	RawBatchPut(context.Context, *aprpcpb.RawBatchPutRequest) (*aprpcpb.RawBatchPutResponse, error)
	RawBatchDelete(context.Context, *aprpcpb.RawBatchDeleteRequest) (*aprpcpb.RawBatchDeleteResponse, error)
}

func RegisterTiapServer(s *grpc.Server, srv TiapServer) {
	s.RegisterService(&_Tiap_serviceDesc, srv)
}

func _Tiap_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawGet(ctx, req.(*aprpcpb.RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawGetKeyTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawGetKeyTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawGetKeyTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawGetKeyTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawGetKeyTTL(ctx, req.(*aprpcpb.RawGetKeyTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawPut(ctx, req.(*aprpcpb.RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawPutWithTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawPutWithTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawPutWithTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawPutWithTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawPutWithTTL(ctx, req.(*aprpcpb.RawPutWithTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawDelete(ctx, req.(*aprpcpb.RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawDeleteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawDeleteRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawDeleteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawDeleteRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawDeleteRange(ctx, req.(*aprpcpb.RawDeleteRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawScan(ctx, req.(*aprpcpb.RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawReverseScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawReverseScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawReverseScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawReverseScan(ctx, req.(*aprpcpb.RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawCompareAndSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawCASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawCompareAndSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawCompareAndSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawCompareAndSwap(ctx, req.(*aprpcpb.RawCASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawBatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawBatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawBatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawBatchGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawBatchGet(ctx, req.(*aprpcpb.RawBatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawBatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawBatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawBatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawBatchPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawBatchPut(ctx, req.(*aprpcpb.RawBatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_RawBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(aprpcpb.RawBatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiappb.Tiap/RawBatchDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawBatchDelete(ctx, req.(*aprpcpb.RawBatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tiap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tiappb.Tiap",
	HandlerType: (*TiapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _Tiap_RawGet_Handler,
		},
		{
			MethodName: "RawGetKeyTTL",
			Handler:    _Tiap_RawGetKeyTTL_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _Tiap_RawPut_Handler,
		},
		{
			MethodName: "RawPutWithTTL",
			Handler:    _Tiap_RawPutWithTTL_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _Tiap_RawDelete_Handler,
		},
		{
			MethodName: "RawDeleteRange",
			Handler:    _Tiap_RawDeleteRange_Handler,
		},
		{
			MethodName: "RawScan",
			Handler:    _Tiap_RawScan_Handler,
		},
		{
			MethodName: "RawReverseScan",
			Handler:    _Tiap_RawReverseScan_Handler,
		},
		{
			MethodName: "RawCompareAndSwap",
			Handler:    _Tiap_RawCompareAndSwap_Handler,
		},
		{
			MethodName: "RawBatchGet",
			Handler:    _Tiap_RawBatchGet_Handler,
		},
		{
			MethodName: "RawBatchPut",
			Handler:    _Tiap_RawBatchPut_Handler,
		},
		{
			MethodName: "RawBatchDelete",
			Handler:    _Tiap_RawBatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiappb.proto",
}

func init() { proto.RegisterFile("tiappb.proto", fileDescriptor_tiappb_58ea8410e8429353) }

var fileDescriptor_tiappb_58ea8410e8429353 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x5b, 0x90, 0x88, 0x6b, 0x2b, 0xba, 0x88, 0x1f, 0xb1, 0xdd, 0x82, 0x0f, 0x50, 0x41,
	0x8f, 0x82, 0xd0, 0x0f, 0x15, 0xfc, 0x80, 0xb2, 0x29, 0x78, 0x9e, 0xd6, 0xa1, 0x2d, 0x68, 0xb2,
	0x26, 0x5b, 0x83, 0x6f, 0xe2, 0x23, 0x79, 0xf4, 0x11, 0xa4, 0xbe, 0x84, 0x47, 0x49, 0xb6, 0xbb,
	0x36, 0xc9, 0xe6, 0xe2, 0x6d, 0xfb, 0xfb, 0xcf, 0xfc, 0x18, 0x3a, 0x13, 0x52, 0x93, 0x33, 0x10,
	0x62, 0xd4, 0x16, 0x61, 0x20, 0x03, 0xea, 0xa8, 0x5f, 0x6e, 0x1d, 0x44, 0x28, 0xc6, 0x1a, 0xbb,
	0xbb, 0x93, 0x60, 0x12, 0xa4, 0xcf, 0x93, 0xe4, 0xa5, 0xe8, 0xe9, 0x8f, 0x43, 0xd6, 0x86, 0x33,
	0x10, 0xf4, 0x9c, 0x38, 0x1c, 0xe2, 0x6b, 0x94, 0x74, 0xaf, 0xad, 0x1b, 0x15, 0xe0, 0xf8, 0x32,
	0xc7, 0x48, 0xba, 0xfb, 0x05, 0x1e, 0x89, 0xc0, 0x8f, 0xf0, 0xb8, 0x42, 0xef, 0x49, 0x4d, 0xb1,
	0x5b, 0x7c, 0x1b, 0x0e, 0xef, 0x68, 0x23, 0x57, 0xaa, 0xb0, 0x16, 0x35, 0x4b, 0x52, 0xa3, 0x53,
	0xb3, 0x0c, 0xe6, 0xb9, 0x59, 0x06, 0x73, 0xfb, 0x2c, 0x29, 0x37, 0xcd, 0x03, 0x52, 0x57, 0xec,
	0x61, 0x26, 0xa7, 0xc9, 0x30, 0xcd, 0x5c, 0xed, 0x92, 0x6b, 0x15, 0x2b, 0x8b, 0x8d, 0xb1, 0x4f,
	0x36, 0x38, 0xc4, 0x7d, 0x7c, 0x42, 0x89, 0xf4, 0x70, 0xb5, 0x5c, 0x31, 0x6d, 0x72, 0x6d, 0x91,
	0xb1, 0x78, 0x64, 0xeb, 0x0f, 0x83, 0x3f, 0x41, 0xca, 0x2c, 0xf5, 0x49, 0xa0, 0x7d, 0xad, 0xd2,
	0xdc, 0x48, 0x2f, 0xc8, 0x3a, 0x87, 0xd8, 0x1b, 0x83, 0x4f, 0x33, 0x7f, 0x49, 0x42, 0xb4, 0xe6,
	0xa0, 0x18, 0x98, 0xfe, 0xcb, 0x74, 0x28, 0x8e, 0xaf, 0x18, 0x46, 0xf8, 0x7f, 0xcd, 0x15, 0xd9,
	0xe1, 0x10, 0xf7, 0x82, 0x67, 0x01, 0x21, 0x76, 0xfc, 0x47, 0x2f, 0x06, 0x91, 0xdd, 0x5d, 0xaf,
	0xe3, 0x59, 0x77, 0x97, 0x72, 0xe3, 0xb9, 0x21, 0x9b, 0x1c, 0xe2, 0x2e, 0xc8, 0xf1, 0x34, 0xb9,
	0xc4, 0xa3, 0xd5, 0x4a, 0x4d, 0xb5, 0xa6, 0x61, 0x0f, 0x6d, 0xae, 0xe4, 0x92, 0x8a, 0xae, 0x95,
	0x73, 0x6a, 0xd8, 0xc3, 0xdc, 0xee, 0xd2, 0x60, 0x79, 0x06, 0xac, 0xd0, 0x91, 0xbd, 0x85, 0x56,
	0x69, 0xae, 0xa5, 0xdd, 0xed, 0x8f, 0x05, 0xab, 0x7e, 0x2e, 0x58, 0xf5, 0x6b, 0xc1, 0xaa, 0xef,
	0xdf, 0xac, 0x32, 0x72, 0xd2, 0x6f, 0xf2, 0xec, 0x37, 0x00, 0x00, 0xff, 0xff, 0x37, 0x52, 0x10,
	0xf7, 0xd0, 0x03, 0x00, 0x00,
}
