// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiappb.proto

package com.shopee.di.kvstore.proto;

public final class Tiappb {
  private Tiappb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014tiappb.proto\022\016tiap_servicepb\032\026tiap_raw" +
      "_kvrpcpb.proto\032\034tiap_hbaselike_kvrpcpb.p" +
      "roto\032\025tiap_adminrpcpb.proto\032\031tiap_raw_ad" +
      "minrpcpb.proto\032\037tiap_hbaselike_adminrpcp" +
      "b.proto2\246\001\n\006TiapKV\022D\n\005RawKV\022\033.tiap_raw_k" +
      "vrpcpb.KVRequest\032\034.tiap_raw_kvrpcpb.KVRe" +
      "sponse\"\000\022V\n\013HBaseLikeKV\022!.tiap_hbaselike" +
      "_kvrpcpb.KVRequest\032\".tiap_hbaselike_kvrp" +
      "cpb.KVResponse\"\0002\235\002\n\tTiapAdmin\022J\n\007DBAdmi" +
      "n\022\035.tiap_adminrpcpb.AdminRequest\032\036.tiap_" +
      "adminrpcpb.AdminResponse\"\000\022X\n\rRawTableAd" +
      "min\022!.tiap_raw_adminrpcpb.AdminRequest\032\"" +
      ".tiap_raw_adminrpcpb.AdminResponse\"\000\022j\n\023" +
      "HBaseLikeTableAdmin\022\'.tiap_hbaselike_adm" +
      "inrpcpb.AdminRequest\032(.tiap_hbaselike_ad" +
      "minrpcpb.AdminResponse\"\000B\035\n\033com.shopee.d" +
      "i.kvstore.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shopee.di.kvstore.proto.TiapRawKvrpcpb.getDescriptor(),
          com.shopee.di.kvstore.proto.TiapHbaselikeKvrpcpb.getDescriptor(),
          com.shopee.di.kvstore.proto.TiapAdminrpcpb.getDescriptor(),
          com.shopee.di.kvstore.proto.TiapRawAdminrpcpb.getDescriptor(),
          com.shopee.di.kvstore.proto.TiapHbaselikeAdminrpcpb.getDescriptor(),
        });
    com.shopee.di.kvstore.proto.TiapRawKvrpcpb.getDescriptor();
    com.shopee.di.kvstore.proto.TiapHbaselikeKvrpcpb.getDescriptor();
    com.shopee.di.kvstore.proto.TiapAdminrpcpb.getDescriptor();
    com.shopee.di.kvstore.proto.TiapRawAdminrpcpb.getDescriptor();
    com.shopee.di.kvstore.proto.TiapHbaselikeAdminrpcpb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
