// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tiap_servicepb.proto

package tiap_servicepb

import (
	"fmt"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	tiap_hbaselike_kvrpcpb "github.com/tutububug/kvproto/pkg/tiap_hbaselike_kvrpcpb"

	tiap_raw_kvrpcpb "github.com/tutububug/kvproto/pkg/tiap_raw_kvrpcpb"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tiap service

type TiapClient interface {
	RawKV(ctx context.Context, in *tiap_raw_kvrpcpb.KVRequest, opts ...grpc.CallOption) (*tiap_raw_kvrpcpb.KVResponse, error)
	HBaseLikeKV(ctx context.Context, in *tiap_hbaselike_kvrpcpb.KVRequest, opts ...grpc.CallOption) (*tiap_hbaselike_kvrpcpb.KVResponse, error)
}

type tiapClient struct {
	cc *grpc.ClientConn
}

func NewTiapClient(cc *grpc.ClientConn) TiapClient {
	return &tiapClient{cc}
}

func (c *tiapClient) RawKV(ctx context.Context, in *tiap_raw_kvrpcpb.KVRequest, opts ...grpc.CallOption) (*tiap_raw_kvrpcpb.KVResponse, error) {
	out := new(tiap_raw_kvrpcpb.KVResponse)
	err := c.cc.Invoke(ctx, "/tiap_servicepb.Tiap/RawKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiapClient) HBaseLikeKV(ctx context.Context, in *tiap_hbaselike_kvrpcpb.KVRequest, opts ...grpc.CallOption) (*tiap_hbaselike_kvrpcpb.KVResponse, error) {
	out := new(tiap_hbaselike_kvrpcpb.KVResponse)
	err := c.cc.Invoke(ctx, "/tiap_servicepb.Tiap/HBaseLikeKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tiap service

type TiapServer interface {
	RawKV(context.Context, *tiap_raw_kvrpcpb.KVRequest) (*tiap_raw_kvrpcpb.KVResponse, error)
	HBaseLikeKV(context.Context, *tiap_hbaselike_kvrpcpb.KVRequest) (*tiap_hbaselike_kvrpcpb.KVResponse, error)
}

func RegisterTiapServer(s *grpc.Server, srv TiapServer) {
	s.RegisterService(&_Tiap_serviceDesc, srv)
}

func _Tiap_RawKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(tiap_raw_kvrpcpb.KVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).RawKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiap_servicepb.Tiap/RawKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).RawKV(ctx, req.(*tiap_raw_kvrpcpb.KVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tiap_HBaseLikeKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(tiap_hbaselike_kvrpcpb.KVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TiapServer).HBaseLikeKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tiap_servicepb.Tiap/HBaseLikeKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TiapServer).HBaseLikeKV(ctx, req.(*tiap_hbaselike_kvrpcpb.KVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tiap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tiap_servicepb.Tiap",
	HandlerType: (*TiapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawKV",
			Handler:    _Tiap_RawKV_Handler,
		},
		{
			MethodName: "HBaseLikeKV",
			Handler:    _Tiap_HBaseLikeKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiap_servicepb.proto",
}

func init() {
	proto.RegisterFile("tiap_servicepb.proto", fileDescriptor_tiap_servicepb_c55a32782897fbcb)
}

var fileDescriptor_tiap_servicepb_c55a32782897fbcb = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xc9, 0x4c, 0x2c,
	0x88, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x4b, 0xe9, 0x83, 0x58, 0x10,
	0x55, 0x52, 0x62, 0x60, 0x55, 0x45, 0x89, 0xe5, 0xf1, 0xd9, 0x65, 0x45, 0x05, 0xc9, 0x30, 0xdd,
	0x52, 0x32, 0x60, 0xf1, 0x8c, 0xa4, 0xc4, 0xe2, 0xd4, 0x9c, 0xcc, 0xec, 0x54, 0x54, 0x59, 0xa3,
	0x25, 0x8c, 0x5c, 0x2c, 0x21, 0x99, 0x89, 0x05, 0x42, 0x2e, 0x5c, 0xac, 0x41, 0x89, 0xe5, 0xde,
	0x61, 0x42, 0xd2, 0x7a, 0x18, 0x06, 0x79, 0x87, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x48,
	0xc9, 0x60, 0x97, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x62, 0x10, 0x0a, 0xe3, 0xe2, 0xf6,
	0x70, 0x4a, 0x2c, 0x4e, 0xf5, 0xc9, 0xcc, 0x4e, 0xf5, 0x0e, 0x13, 0x52, 0xd4, 0xc3, 0x61, 0x39,
	0xc2, 0x44, 0x25, 0x7c, 0x4a, 0x60, 0xe6, 0x3a, 0x09, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91,
	0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x33, 0x1e, 0xcb, 0x31, 0x24, 0xb1, 0x81, 0xdd, 0x6f, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xff, 0x04, 0x91, 0x33, 0x01, 0x00, 0x00,
}
