// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replication_modepb.proto

package replication_modepb;

public final class ReplicationModepb {
  private ReplicationModepb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code replication_modepb.ReplicationMode}
   */
  public enum ReplicationMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The standard mode. Replicate logs to majority peer.
     * </pre>
     *
     * <code>MAJORITY = 0;</code>
     */
    MAJORITY(0),
    /**
     * <pre>
     * DR mode. Replicate logs among 2 DCs.
     * </pre>
     *
     * <code>DR_AUTO_SYNC = 1;</code>
     */
    DR_AUTO_SYNC(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The standard mode. Replicate logs to majority peer.
     * </pre>
     *
     * <code>MAJORITY = 0;</code>
     */
    public static final int MAJORITY_VALUE = 0;
    /**
     * <pre>
     * DR mode. Replicate logs among 2 DCs.
     * </pre>
     *
     * <code>DR_AUTO_SYNC = 1;</code>
     */
    public static final int DR_AUTO_SYNC_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReplicationMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ReplicationMode forNumber(int value) {
      switch (value) {
        case 0: return MAJORITY;
        case 1: return DR_AUTO_SYNC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReplicationMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReplicationMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReplicationMode>() {
            public ReplicationMode findValueByNumber(int number) {
              return ReplicationMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReplicationMode[] VALUES = values();

    public static ReplicationMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReplicationMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:replication_modepb.ReplicationMode)
  }

  /**
   * Protobuf enum {@code replication_modepb.DRAutoSyncState}
   */
  public enum DRAutoSyncState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Raft logs need to sync between different DCs
     * </pre>
     *
     * <code>SYNC = 0;</code>
     */
    SYNC(0),
    /**
     * <pre>
     * Raft logs need to sync to majority peers
     * </pre>
     *
     * <code>ASYNC = 1;</code>
     */
    ASYNC(1),
    /**
     * <pre>
     * Switching from ASYNC to SYNC mode
     * </pre>
     *
     * <code>SYNC_RECOVER = 2;</code>
     */
    SYNC_RECOVER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Raft logs need to sync between different DCs
     * </pre>
     *
     * <code>SYNC = 0;</code>
     */
    public static final int SYNC_VALUE = 0;
    /**
     * <pre>
     * Raft logs need to sync to majority peers
     * </pre>
     *
     * <code>ASYNC = 1;</code>
     */
    public static final int ASYNC_VALUE = 1;
    /**
     * <pre>
     * Switching from ASYNC to SYNC mode
     * </pre>
     *
     * <code>SYNC_RECOVER = 2;</code>
     */
    public static final int SYNC_RECOVER_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DRAutoSyncState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DRAutoSyncState forNumber(int value) {
      switch (value) {
        case 0: return SYNC;
        case 1: return ASYNC;
        case 2: return SYNC_RECOVER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DRAutoSyncState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DRAutoSyncState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DRAutoSyncState>() {
            public DRAutoSyncState findValueByNumber(int number) {
              return DRAutoSyncState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.getDescriptor().getEnumTypes().get(1);
    }

    private static final DRAutoSyncState[] VALUES = values();

    public static DRAutoSyncState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DRAutoSyncState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:replication_modepb.DRAutoSyncState)
  }

  /**
   * Protobuf enum {@code replication_modepb.RegionReplicationState}
   */
  public enum RegionReplicationState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The region's state is unknown
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Logs sync to majority peers
     * </pre>
     *
     * <code>SIMPLE_MAJORITY = 1;</code>
     */
    SIMPLE_MAJORITY(1),
    /**
     * <pre>
     * Logs sync to different DCs
     * </pre>
     *
     * <code>INTEGRITY_OVER_LABEL = 2;</code>
     */
    INTEGRITY_OVER_LABEL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The region's state is unknown
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Logs sync to majority peers
     * </pre>
     *
     * <code>SIMPLE_MAJORITY = 1;</code>
     */
    public static final int SIMPLE_MAJORITY_VALUE = 1;
    /**
     * <pre>
     * Logs sync to different DCs
     * </pre>
     *
     * <code>INTEGRITY_OVER_LABEL = 2;</code>
     */
    public static final int INTEGRITY_OVER_LABEL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RegionReplicationState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RegionReplicationState forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return SIMPLE_MAJORITY;
        case 2: return INTEGRITY_OVER_LABEL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RegionReplicationState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RegionReplicationState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RegionReplicationState>() {
            public RegionReplicationState findValueByNumber(int number) {
              return RegionReplicationState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.getDescriptor().getEnumTypes().get(2);
    }

    private static final RegionReplicationState[] VALUES = values();

    public static RegionReplicationState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RegionReplicationState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:replication_modepb.RegionReplicationState)
  }

  public interface ReplicationStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:replication_modepb.ReplicationStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.replication_modepb.ReplicationMode mode = 1;</code>
     * @return The enum numeric value on the wire for mode.
     */
    int getModeValue();
    /**
     * <code>.replication_modepb.ReplicationMode mode = 1;</code>
     * @return The mode.
     */
    replication_modepb.ReplicationModepb.ReplicationMode getMode();

    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     * @return Whether the drAutoSync field is set.
     */
    boolean hasDrAutoSync();
    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     * @return The drAutoSync.
     */
    replication_modepb.ReplicationModepb.DRAutoSync getDrAutoSync();
    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     */
    replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder getDrAutoSyncOrBuilder();
  }
  /**
   * <pre>
   * The replication status sync from PD to TiKV.
   * </pre>
   *
   * Protobuf type {@code replication_modepb.ReplicationStatus}
   */
  public static final class ReplicationStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:replication_modepb.ReplicationStatus)
      ReplicationStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReplicationStatus.newBuilder() to construct.
    private ReplicationStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplicationStatus() {
      mode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReplicationStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReplicationStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              mode_ = rawValue;
              break;
            }
            case 18: {
              replication_modepb.ReplicationModepb.DRAutoSync.Builder subBuilder = null;
              if (drAutoSync_ != null) {
                subBuilder = drAutoSync_.toBuilder();
              }
              drAutoSync_ = input.readMessage(replication_modepb.ReplicationModepb.DRAutoSync.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(drAutoSync_);
                drAutoSync_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_ReplicationStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_ReplicationStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              replication_modepb.ReplicationModepb.ReplicationStatus.class, replication_modepb.ReplicationModepb.ReplicationStatus.Builder.class);
    }

    public static final int MODE_FIELD_NUMBER = 1;
    private int mode_;
    /**
     * <code>.replication_modepb.ReplicationMode mode = 1;</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <code>.replication_modepb.ReplicationMode mode = 1;</code>
     * @return The mode.
     */
    @java.lang.Override public replication_modepb.ReplicationModepb.ReplicationMode getMode() {
      @SuppressWarnings("deprecation")
      replication_modepb.ReplicationModepb.ReplicationMode result = replication_modepb.ReplicationModepb.ReplicationMode.valueOf(mode_);
      return result == null ? replication_modepb.ReplicationModepb.ReplicationMode.UNRECOGNIZED : result;
    }

    public static final int DR_AUTO_SYNC_FIELD_NUMBER = 2;
    private replication_modepb.ReplicationModepb.DRAutoSync drAutoSync_;
    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     * @return Whether the drAutoSync field is set.
     */
    @java.lang.Override
    public boolean hasDrAutoSync() {
      return drAutoSync_ != null;
    }
    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     * @return The drAutoSync.
     */
    @java.lang.Override
    public replication_modepb.ReplicationModepb.DRAutoSync getDrAutoSync() {
      return drAutoSync_ == null ? replication_modepb.ReplicationModepb.DRAutoSync.getDefaultInstance() : drAutoSync_;
    }
    /**
     * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
     */
    @java.lang.Override
    public replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder getDrAutoSyncOrBuilder() {
      return getDrAutoSync();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mode_ != replication_modepb.ReplicationModepb.ReplicationMode.MAJORITY.getNumber()) {
        output.writeEnum(1, mode_);
      }
      if (drAutoSync_ != null) {
        output.writeMessage(2, getDrAutoSync());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mode_ != replication_modepb.ReplicationModepb.ReplicationMode.MAJORITY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mode_);
      }
      if (drAutoSync_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDrAutoSync());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof replication_modepb.ReplicationModepb.ReplicationStatus)) {
        return super.equals(obj);
      }
      replication_modepb.ReplicationModepb.ReplicationStatus other = (replication_modepb.ReplicationModepb.ReplicationStatus) obj;

      if (mode_ != other.mode_) return false;
      if (hasDrAutoSync() != other.hasDrAutoSync()) return false;
      if (hasDrAutoSync()) {
        if (!getDrAutoSync()
            .equals(other.getDrAutoSync())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + mode_;
      if (hasDrAutoSync()) {
        hash = (37 * hash) + DR_AUTO_SYNC_FIELD_NUMBER;
        hash = (53 * hash) + getDrAutoSync().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.ReplicationStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(replication_modepb.ReplicationModepb.ReplicationStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The replication status sync from PD to TiKV.
     * </pre>
     *
     * Protobuf type {@code replication_modepb.ReplicationStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:replication_modepb.ReplicationStatus)
        replication_modepb.ReplicationModepb.ReplicationStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_ReplicationStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_ReplicationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                replication_modepb.ReplicationModepb.ReplicationStatus.class, replication_modepb.ReplicationModepb.ReplicationStatus.Builder.class);
      }

      // Construct using replication_modepb.ReplicationModepb.ReplicationStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mode_ = 0;

        if (drAutoSyncBuilder_ == null) {
          drAutoSync_ = null;
        } else {
          drAutoSync_ = null;
          drAutoSyncBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_ReplicationStatus_descriptor;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.ReplicationStatus getDefaultInstanceForType() {
        return replication_modepb.ReplicationModepb.ReplicationStatus.getDefaultInstance();
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.ReplicationStatus build() {
        replication_modepb.ReplicationModepb.ReplicationStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.ReplicationStatus buildPartial() {
        replication_modepb.ReplicationModepb.ReplicationStatus result = new replication_modepb.ReplicationModepb.ReplicationStatus(this);
        result.mode_ = mode_;
        if (drAutoSyncBuilder_ == null) {
          result.drAutoSync_ = drAutoSync_;
        } else {
          result.drAutoSync_ = drAutoSyncBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof replication_modepb.ReplicationModepb.ReplicationStatus) {
          return mergeFrom((replication_modepb.ReplicationModepb.ReplicationStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(replication_modepb.ReplicationModepb.ReplicationStatus other) {
        if (other == replication_modepb.ReplicationModepb.ReplicationStatus.getDefaultInstance()) return this;
        if (other.mode_ != 0) {
          setModeValue(other.getModeValue());
        }
        if (other.hasDrAutoSync()) {
          mergeDrAutoSync(other.getDrAutoSync());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        replication_modepb.ReplicationModepb.ReplicationStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (replication_modepb.ReplicationModepb.ReplicationStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mode_ = 0;
      /**
       * <code>.replication_modepb.ReplicationMode mode = 1;</code>
       * @return The enum numeric value on the wire for mode.
       */
      @java.lang.Override public int getModeValue() {
        return mode_;
      }
      /**
       * <code>.replication_modepb.ReplicationMode mode = 1;</code>
       * @param value The enum numeric value on the wire for mode to set.
       * @return This builder for chaining.
       */
      public Builder setModeValue(int value) {
        
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.ReplicationMode mode = 1;</code>
       * @return The mode.
       */
      @java.lang.Override
      public replication_modepb.ReplicationModepb.ReplicationMode getMode() {
        @SuppressWarnings("deprecation")
        replication_modepb.ReplicationModepb.ReplicationMode result = replication_modepb.ReplicationModepb.ReplicationMode.valueOf(mode_);
        return result == null ? replication_modepb.ReplicationModepb.ReplicationMode.UNRECOGNIZED : result;
      }
      /**
       * <code>.replication_modepb.ReplicationMode mode = 1;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(replication_modepb.ReplicationModepb.ReplicationMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.ReplicationMode mode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        
        mode_ = 0;
        onChanged();
        return this;
      }

      private replication_modepb.ReplicationModepb.DRAutoSync drAutoSync_;
      private com.google.protobuf.SingleFieldBuilderV3<
          replication_modepb.ReplicationModepb.DRAutoSync, replication_modepb.ReplicationModepb.DRAutoSync.Builder, replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder> drAutoSyncBuilder_;
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       * @return Whether the drAutoSync field is set.
       */
      public boolean hasDrAutoSync() {
        return drAutoSyncBuilder_ != null || drAutoSync_ != null;
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       * @return The drAutoSync.
       */
      public replication_modepb.ReplicationModepb.DRAutoSync getDrAutoSync() {
        if (drAutoSyncBuilder_ == null) {
          return drAutoSync_ == null ? replication_modepb.ReplicationModepb.DRAutoSync.getDefaultInstance() : drAutoSync_;
        } else {
          return drAutoSyncBuilder_.getMessage();
        }
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public Builder setDrAutoSync(replication_modepb.ReplicationModepb.DRAutoSync value) {
        if (drAutoSyncBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          drAutoSync_ = value;
          onChanged();
        } else {
          drAutoSyncBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public Builder setDrAutoSync(
          replication_modepb.ReplicationModepb.DRAutoSync.Builder builderForValue) {
        if (drAutoSyncBuilder_ == null) {
          drAutoSync_ = builderForValue.build();
          onChanged();
        } else {
          drAutoSyncBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public Builder mergeDrAutoSync(replication_modepb.ReplicationModepb.DRAutoSync value) {
        if (drAutoSyncBuilder_ == null) {
          if (drAutoSync_ != null) {
            drAutoSync_ =
              replication_modepb.ReplicationModepb.DRAutoSync.newBuilder(drAutoSync_).mergeFrom(value).buildPartial();
          } else {
            drAutoSync_ = value;
          }
          onChanged();
        } else {
          drAutoSyncBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public Builder clearDrAutoSync() {
        if (drAutoSyncBuilder_ == null) {
          drAutoSync_ = null;
          onChanged();
        } else {
          drAutoSync_ = null;
          drAutoSyncBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public replication_modepb.ReplicationModepb.DRAutoSync.Builder getDrAutoSyncBuilder() {
        
        onChanged();
        return getDrAutoSyncFieldBuilder().getBuilder();
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      public replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder getDrAutoSyncOrBuilder() {
        if (drAutoSyncBuilder_ != null) {
          return drAutoSyncBuilder_.getMessageOrBuilder();
        } else {
          return drAutoSync_ == null ?
              replication_modepb.ReplicationModepb.DRAutoSync.getDefaultInstance() : drAutoSync_;
        }
      }
      /**
       * <code>.replication_modepb.DRAutoSync dr_auto_sync = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          replication_modepb.ReplicationModepb.DRAutoSync, replication_modepb.ReplicationModepb.DRAutoSync.Builder, replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder> 
          getDrAutoSyncFieldBuilder() {
        if (drAutoSyncBuilder_ == null) {
          drAutoSyncBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              replication_modepb.ReplicationModepb.DRAutoSync, replication_modepb.ReplicationModepb.DRAutoSync.Builder, replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder>(
                  getDrAutoSync(),
                  getParentForChildren(),
                  isClean());
          drAutoSync_ = null;
        }
        return drAutoSyncBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:replication_modepb.ReplicationStatus)
    }

    // @@protoc_insertion_point(class_scope:replication_modepb.ReplicationStatus)
    private static final replication_modepb.ReplicationModepb.ReplicationStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new replication_modepb.ReplicationModepb.ReplicationStatus();
    }

    public static replication_modepb.ReplicationModepb.ReplicationStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplicationStatus>
        PARSER = new com.google.protobuf.AbstractParser<ReplicationStatus>() {
      @java.lang.Override
      public ReplicationStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplicationStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReplicationStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplicationStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public replication_modepb.ReplicationModepb.ReplicationStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DRAutoSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:replication_modepb.DRAutoSync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The key of the label that used for distinguish different DC.
     * </pre>
     *
     * <code>string label_key = 1;</code>
     * @return The labelKey.
     */
    java.lang.String getLabelKey();
    /**
     * <pre>
     * The key of the label that used for distinguish different DC.
     * </pre>
     *
     * <code>string label_key = 1;</code>
     * @return The bytes for labelKey.
     */
    com.google.protobuf.ByteString
        getLabelKeyBytes();

    /**
     * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @return The state.
     */
    replication_modepb.ReplicationModepb.DRAutoSyncState getState();

    /**
     * <pre>
     * Unique ID of the state, it increases after each state transfer.
     * </pre>
     *
     * <code>uint64 state_id = 3;</code>
     * @return The stateId.
     */
    long getStateId();

    /**
     * <pre>
     * Duration to wait before switching to SYNC by force (in seconds)
     * </pre>
     *
     * <code>int32 wait_sync_timeout_hint = 4;</code>
     * @return The waitSyncTimeoutHint.
     */
    int getWaitSyncTimeoutHint();
  }
  /**
   * <pre>
   * The status of dr-autosync mode.
   * </pre>
   *
   * Protobuf type {@code replication_modepb.DRAutoSync}
   */
  public static final class DRAutoSync extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:replication_modepb.DRAutoSync)
      DRAutoSyncOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DRAutoSync.newBuilder() to construct.
    private DRAutoSync(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DRAutoSync() {
      labelKey_ = "";
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DRAutoSync();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DRAutoSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              labelKey_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 24: {

              stateId_ = input.readUInt64();
              break;
            }
            case 32: {

              waitSyncTimeoutHint_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_DRAutoSync_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_DRAutoSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              replication_modepb.ReplicationModepb.DRAutoSync.class, replication_modepb.ReplicationModepb.DRAutoSync.Builder.class);
    }

    public static final int LABEL_KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object labelKey_;
    /**
     * <pre>
     * The key of the label that used for distinguish different DC.
     * </pre>
     *
     * <code>string label_key = 1;</code>
     * @return The labelKey.
     */
    @java.lang.Override
    public java.lang.String getLabelKey() {
      java.lang.Object ref = labelKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        labelKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The key of the label that used for distinguish different DC.
     * </pre>
     *
     * <code>string label_key = 1;</code>
     * @return The bytes for labelKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelKeyBytes() {
      java.lang.Object ref = labelKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        labelKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @return The state.
     */
    @java.lang.Override public replication_modepb.ReplicationModepb.DRAutoSyncState getState() {
      @SuppressWarnings("deprecation")
      replication_modepb.ReplicationModepb.DRAutoSyncState result = replication_modepb.ReplicationModepb.DRAutoSyncState.valueOf(state_);
      return result == null ? replication_modepb.ReplicationModepb.DRAutoSyncState.UNRECOGNIZED : result;
    }

    public static final int STATE_ID_FIELD_NUMBER = 3;
    private long stateId_;
    /**
     * <pre>
     * Unique ID of the state, it increases after each state transfer.
     * </pre>
     *
     * <code>uint64 state_id = 3;</code>
     * @return The stateId.
     */
    @java.lang.Override
    public long getStateId() {
      return stateId_;
    }

    public static final int WAIT_SYNC_TIMEOUT_HINT_FIELD_NUMBER = 4;
    private int waitSyncTimeoutHint_;
    /**
     * <pre>
     * Duration to wait before switching to SYNC by force (in seconds)
     * </pre>
     *
     * <code>int32 wait_sync_timeout_hint = 4;</code>
     * @return The waitSyncTimeoutHint.
     */
    @java.lang.Override
    public int getWaitSyncTimeoutHint() {
      return waitSyncTimeoutHint_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLabelKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, labelKey_);
      }
      if (state_ != replication_modepb.ReplicationModepb.DRAutoSyncState.SYNC.getNumber()) {
        output.writeEnum(2, state_);
      }
      if (stateId_ != 0L) {
        output.writeUInt64(3, stateId_);
      }
      if (waitSyncTimeoutHint_ != 0) {
        output.writeInt32(4, waitSyncTimeoutHint_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLabelKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, labelKey_);
      }
      if (state_ != replication_modepb.ReplicationModepb.DRAutoSyncState.SYNC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      if (stateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, stateId_);
      }
      if (waitSyncTimeoutHint_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, waitSyncTimeoutHint_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof replication_modepb.ReplicationModepb.DRAutoSync)) {
        return super.equals(obj);
      }
      replication_modepb.ReplicationModepb.DRAutoSync other = (replication_modepb.ReplicationModepb.DRAutoSync) obj;

      if (!getLabelKey()
          .equals(other.getLabelKey())) return false;
      if (state_ != other.state_) return false;
      if (getStateId()
          != other.getStateId()) return false;
      if (getWaitSyncTimeoutHint()
          != other.getWaitSyncTimeoutHint()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABEL_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getLabelKey().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + STATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStateId());
      hash = (37 * hash) + WAIT_SYNC_TIMEOUT_HINT_FIELD_NUMBER;
      hash = (53 * hash) + getWaitSyncTimeoutHint();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.DRAutoSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(replication_modepb.ReplicationModepb.DRAutoSync prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The status of dr-autosync mode.
     * </pre>
     *
     * Protobuf type {@code replication_modepb.DRAutoSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:replication_modepb.DRAutoSync)
        replication_modepb.ReplicationModepb.DRAutoSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_DRAutoSync_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_DRAutoSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                replication_modepb.ReplicationModepb.DRAutoSync.class, replication_modepb.ReplicationModepb.DRAutoSync.Builder.class);
      }

      // Construct using replication_modepb.ReplicationModepb.DRAutoSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        labelKey_ = "";

        state_ = 0;

        stateId_ = 0L;

        waitSyncTimeoutHint_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_DRAutoSync_descriptor;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.DRAutoSync getDefaultInstanceForType() {
        return replication_modepb.ReplicationModepb.DRAutoSync.getDefaultInstance();
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.DRAutoSync build() {
        replication_modepb.ReplicationModepb.DRAutoSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.DRAutoSync buildPartial() {
        replication_modepb.ReplicationModepb.DRAutoSync result = new replication_modepb.ReplicationModepb.DRAutoSync(this);
        result.labelKey_ = labelKey_;
        result.state_ = state_;
        result.stateId_ = stateId_;
        result.waitSyncTimeoutHint_ = waitSyncTimeoutHint_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof replication_modepb.ReplicationModepb.DRAutoSync) {
          return mergeFrom((replication_modepb.ReplicationModepb.DRAutoSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(replication_modepb.ReplicationModepb.DRAutoSync other) {
        if (other == replication_modepb.ReplicationModepb.DRAutoSync.getDefaultInstance()) return this;
        if (!other.getLabelKey().isEmpty()) {
          labelKey_ = other.labelKey_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getStateId() != 0L) {
          setStateId(other.getStateId());
        }
        if (other.getWaitSyncTimeoutHint() != 0) {
          setWaitSyncTimeoutHint(other.getWaitSyncTimeoutHint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        replication_modepb.ReplicationModepb.DRAutoSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (replication_modepb.ReplicationModepb.DRAutoSync) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object labelKey_ = "";
      /**
       * <pre>
       * The key of the label that used for distinguish different DC.
       * </pre>
       *
       * <code>string label_key = 1;</code>
       * @return The labelKey.
       */
      public java.lang.String getLabelKey() {
        java.lang.Object ref = labelKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          labelKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The key of the label that used for distinguish different DC.
       * </pre>
       *
       * <code>string label_key = 1;</code>
       * @return The bytes for labelKey.
       */
      public com.google.protobuf.ByteString
          getLabelKeyBytes() {
        java.lang.Object ref = labelKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          labelKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The key of the label that used for distinguish different DC.
       * </pre>
       *
       * <code>string label_key = 1;</code>
       * @param value The labelKey to set.
       * @return This builder for chaining.
       */
      public Builder setLabelKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        labelKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key of the label that used for distinguish different DC.
       * </pre>
       *
       * <code>string label_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabelKey() {
        
        labelKey_ = getDefaultInstance().getLabelKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key of the label that used for distinguish different DC.
       * </pre>
       *
       * <code>string label_key = 1;</code>
       * @param value The bytes for labelKey to set.
       * @return This builder for chaining.
       */
      public Builder setLabelKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        labelKey_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
       * @return The state.
       */
      @java.lang.Override
      public replication_modepb.ReplicationModepb.DRAutoSyncState getState() {
        @SuppressWarnings("deprecation")
        replication_modepb.ReplicationModepb.DRAutoSyncState result = replication_modepb.ReplicationModepb.DRAutoSyncState.valueOf(state_);
        return result == null ? replication_modepb.ReplicationModepb.DRAutoSyncState.UNRECOGNIZED : result;
      }
      /**
       * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(replication_modepb.ReplicationModepb.DRAutoSyncState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.DRAutoSyncState state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private long stateId_ ;
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 3;</code>
       * @return The stateId.
       */
      @java.lang.Override
      public long getStateId() {
        return stateId_;
      }
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 3;</code>
       * @param value The stateId to set.
       * @return This builder for chaining.
       */
      public Builder setStateId(long value) {
        
        stateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateId() {
        
        stateId_ = 0L;
        onChanged();
        return this;
      }

      private int waitSyncTimeoutHint_ ;
      /**
       * <pre>
       * Duration to wait before switching to SYNC by force (in seconds)
       * </pre>
       *
       * <code>int32 wait_sync_timeout_hint = 4;</code>
       * @return The waitSyncTimeoutHint.
       */
      @java.lang.Override
      public int getWaitSyncTimeoutHint() {
        return waitSyncTimeoutHint_;
      }
      /**
       * <pre>
       * Duration to wait before switching to SYNC by force (in seconds)
       * </pre>
       *
       * <code>int32 wait_sync_timeout_hint = 4;</code>
       * @param value The waitSyncTimeoutHint to set.
       * @return This builder for chaining.
       */
      public Builder setWaitSyncTimeoutHint(int value) {
        
        waitSyncTimeoutHint_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Duration to wait before switching to SYNC by force (in seconds)
       * </pre>
       *
       * <code>int32 wait_sync_timeout_hint = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWaitSyncTimeoutHint() {
        
        waitSyncTimeoutHint_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:replication_modepb.DRAutoSync)
    }

    // @@protoc_insertion_point(class_scope:replication_modepb.DRAutoSync)
    private static final replication_modepb.ReplicationModepb.DRAutoSync DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new replication_modepb.ReplicationModepb.DRAutoSync();
    }

    public static replication_modepb.ReplicationModepb.DRAutoSync getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DRAutoSync>
        PARSER = new com.google.protobuf.AbstractParser<DRAutoSync>() {
      @java.lang.Override
      public DRAutoSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DRAutoSync(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DRAutoSync> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DRAutoSync> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public replication_modepb.ReplicationModepb.DRAutoSync getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegionReplicationStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:replication_modepb.RegionReplicationStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.replication_modepb.RegionReplicationState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.replication_modepb.RegionReplicationState state = 1;</code>
     * @return The state.
     */
    replication_modepb.ReplicationModepb.RegionReplicationState getState();

    /**
     * <pre>
     * Unique ID of the state, it increases after each state transfer.
     * </pre>
     *
     * <code>uint64 state_id = 2;</code>
     * @return The stateId.
     */
    long getStateId();
  }
  /**
   * <pre>
   * The replication status sync from TiKV to PD.
   * </pre>
   *
   * Protobuf type {@code replication_modepb.RegionReplicationStatus}
   */
  public static final class RegionReplicationStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:replication_modepb.RegionReplicationStatus)
      RegionReplicationStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegionReplicationStatus.newBuilder() to construct.
    private RegionReplicationStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegionReplicationStatus() {
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegionReplicationStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegionReplicationStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 16: {

              stateId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_RegionReplicationStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return replication_modepb.ReplicationModepb.internal_static_replication_modepb_RegionReplicationStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              replication_modepb.ReplicationModepb.RegionReplicationStatus.class, replication_modepb.ReplicationModepb.RegionReplicationStatus.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>.replication_modepb.RegionReplicationState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.replication_modepb.RegionReplicationState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override public replication_modepb.ReplicationModepb.RegionReplicationState getState() {
      @SuppressWarnings("deprecation")
      replication_modepb.ReplicationModepb.RegionReplicationState result = replication_modepb.ReplicationModepb.RegionReplicationState.valueOf(state_);
      return result == null ? replication_modepb.ReplicationModepb.RegionReplicationState.UNRECOGNIZED : result;
    }

    public static final int STATE_ID_FIELD_NUMBER = 2;
    private long stateId_;
    /**
     * <pre>
     * Unique ID of the state, it increases after each state transfer.
     * </pre>
     *
     * <code>uint64 state_id = 2;</code>
     * @return The stateId.
     */
    @java.lang.Override
    public long getStateId() {
      return stateId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != replication_modepb.ReplicationModepb.RegionReplicationState.UNKNOWN.getNumber()) {
        output.writeEnum(1, state_);
      }
      if (stateId_ != 0L) {
        output.writeUInt64(2, stateId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != replication_modepb.ReplicationModepb.RegionReplicationState.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (stateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, stateId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof replication_modepb.ReplicationModepb.RegionReplicationStatus)) {
        return super.equals(obj);
      }
      replication_modepb.ReplicationModepb.RegionReplicationStatus other = (replication_modepb.ReplicationModepb.RegionReplicationStatus) obj;

      if (state_ != other.state_) return false;
      if (getStateId()
          != other.getStateId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + STATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStateId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static replication_modepb.ReplicationModepb.RegionReplicationStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(replication_modepb.ReplicationModepb.RegionReplicationStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The replication status sync from TiKV to PD.
     * </pre>
     *
     * Protobuf type {@code replication_modepb.RegionReplicationStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:replication_modepb.RegionReplicationStatus)
        replication_modepb.ReplicationModepb.RegionReplicationStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_RegionReplicationStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_RegionReplicationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                replication_modepb.ReplicationModepb.RegionReplicationStatus.class, replication_modepb.ReplicationModepb.RegionReplicationStatus.Builder.class);
      }

      // Construct using replication_modepb.ReplicationModepb.RegionReplicationStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = 0;

        stateId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return replication_modepb.ReplicationModepb.internal_static_replication_modepb_RegionReplicationStatus_descriptor;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.RegionReplicationStatus getDefaultInstanceForType() {
        return replication_modepb.ReplicationModepb.RegionReplicationStatus.getDefaultInstance();
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.RegionReplicationStatus build() {
        replication_modepb.ReplicationModepb.RegionReplicationStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public replication_modepb.ReplicationModepb.RegionReplicationStatus buildPartial() {
        replication_modepb.ReplicationModepb.RegionReplicationStatus result = new replication_modepb.ReplicationModepb.RegionReplicationStatus(this);
        result.state_ = state_;
        result.stateId_ = stateId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof replication_modepb.ReplicationModepb.RegionReplicationStatus) {
          return mergeFrom((replication_modepb.ReplicationModepb.RegionReplicationStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(replication_modepb.ReplicationModepb.RegionReplicationStatus other) {
        if (other == replication_modepb.ReplicationModepb.RegionReplicationStatus.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getStateId() != 0L) {
          setStateId(other.getStateId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        replication_modepb.ReplicationModepb.RegionReplicationStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (replication_modepb.ReplicationModepb.RegionReplicationStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.replication_modepb.RegionReplicationState state = 1;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.replication_modepb.RegionReplicationState state = 1;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.RegionReplicationState state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public replication_modepb.ReplicationModepb.RegionReplicationState getState() {
        @SuppressWarnings("deprecation")
        replication_modepb.ReplicationModepb.RegionReplicationState result = replication_modepb.ReplicationModepb.RegionReplicationState.valueOf(state_);
        return result == null ? replication_modepb.ReplicationModepb.RegionReplicationState.UNRECOGNIZED : result;
      }
      /**
       * <code>.replication_modepb.RegionReplicationState state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(replication_modepb.ReplicationModepb.RegionReplicationState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.replication_modepb.RegionReplicationState state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private long stateId_ ;
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 2;</code>
       * @return The stateId.
       */
      @java.lang.Override
      public long getStateId() {
        return stateId_;
      }
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 2;</code>
       * @param value The stateId to set.
       * @return This builder for chaining.
       */
      public Builder setStateId(long value) {
        
        stateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique ID of the state, it increases after each state transfer.
       * </pre>
       *
       * <code>uint64 state_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateId() {
        
        stateId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:replication_modepb.RegionReplicationStatus)
    }

    // @@protoc_insertion_point(class_scope:replication_modepb.RegionReplicationStatus)
    private static final replication_modepb.ReplicationModepb.RegionReplicationStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new replication_modepb.ReplicationModepb.RegionReplicationStatus();
    }

    public static replication_modepb.ReplicationModepb.RegionReplicationStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegionReplicationStatus>
        PARSER = new com.google.protobuf.AbstractParser<RegionReplicationStatus>() {
      @java.lang.Override
      public RegionReplicationStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegionReplicationStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegionReplicationStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegionReplicationStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public replication_modepb.ReplicationModepb.RegionReplicationStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_replication_modepb_ReplicationStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_replication_modepb_ReplicationStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_replication_modepb_DRAutoSync_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_replication_modepb_DRAutoSync_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_replication_modepb_RegionReplicationStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_replication_modepb_RegionReplicationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030replication_modepb.proto\022\022replication_" +
      "modepb\"|\n\021ReplicationStatus\0221\n\004mode\030\001 \001(" +
      "\0162#.replication_modepb.ReplicationMode\0224" +
      "\n\014dr_auto_sync\030\002 \001(\0132\036.replication_modep" +
      "b.DRAutoSync\"\205\001\n\nDRAutoSync\022\021\n\tlabel_key" +
      "\030\001 \001(\t\0222\n\005state\030\002 \001(\0162#.replication_mode" +
      "pb.DRAutoSyncState\022\020\n\010state_id\030\003 \001(\004\022\036\n\026" +
      "wait_sync_timeout_hint\030\004 \001(\005\"f\n\027RegionRe" +
      "plicationStatus\0229\n\005state\030\001 \001(\0162*.replica" +
      "tion_modepb.RegionReplicationState\022\020\n\010st" +
      "ate_id\030\002 \001(\004*1\n\017ReplicationMode\022\014\n\010MAJOR" +
      "ITY\020\000\022\020\n\014DR_AUTO_SYNC\020\001*8\n\017DRAutoSyncSta" +
      "te\022\010\n\004SYNC\020\000\022\t\n\005ASYNC\020\001\022\020\n\014SYNC_RECOVER\020" +
      "\002*T\n\026RegionReplicationState\022\013\n\007UNKNOWN\020\000" +
      "\022\023\n\017SIMPLE_MAJORITY\020\001\022\030\n\024INTEGRITY_OVER_" +
      "LABEL\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_replication_modepb_ReplicationStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_replication_modepb_ReplicationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_replication_modepb_ReplicationStatus_descriptor,
        new java.lang.String[] { "Mode", "DrAutoSync", });
    internal_static_replication_modepb_DRAutoSync_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_replication_modepb_DRAutoSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_replication_modepb_DRAutoSync_descriptor,
        new java.lang.String[] { "LabelKey", "State", "StateId", "WaitSyncTimeoutHint", });
    internal_static_replication_modepb_RegionReplicationStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_replication_modepb_RegionReplicationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_replication_modepb_RegionReplicationStatus_descriptor,
        new java.lang.String[] { "State", "StateId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
